### ISSUE TITLE
Email confirmation: Separate plasmid and strain table format

### ISSUE THREAD

**Issue by erichartline** [dictyBase/event-messenger#1]
see https://github.com/dictyBase/Dicty-Stock-Center/issues/91

**Comment by pfey03** [comment]
[DSC Order Confirmation.pdf](https://github.com/dictyBase/event-messenger/files/3118813/DSC.Order.Confirmation.pdf)

Sorry added it to closed issue after being out with Bob and a couple of drinks;-)

**Comment by pfey03** [comment]
[DSC Order Confirmation2.pdf](https://github.com/dictyBase/event-messenger/files/3148732/DSC.Order.Confirmation2.pdf)
