### ISSUE TITLE
PO number does not appear

### ISSUE THREAD

**Issue by oimartin** [dictyBase/event-messenger#71]
**PO number is not visible on either the GitHub issue or the user confirmation email**
__________
__________
![image](https://user-images.githubusercontent.com/29387347/99430178-9dc15800-28ce-11eb-8601-e606253de182.png)
![image](https://user-images.githubusercontent.com/29387347/99430274-be89ad80-28ce-11eb-8502-bea4ceaf434e.png)

**Comment by erichartline** [comment]
I looked at some sent orders -- the purchase order number is correctly sent through the `purchase_order_num` field in GraphQL. This is accessible through `PurchaseOrderNum` in `OrderAttributes` in the order protocol buffer.
